permalink: /:2026:08:23/:Writing-Enhanced Courses (WEC)
url: https://writingisthinking.github.io/writing-enhanced-courses-wec/
baseurl: /project

# variables
name: Writing-Enhanced Courses (WEC)
description: Dr. Vyshali Manivannan's open-access WEC repository in protest of Pace University's removal of administrative release time and contractual protections for the WEC Director role.
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true